apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-kubernetes-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-kubernetes
  template:
    metadata:
      labels:
        app: docker-kubernetes
    spec:
      containers:
        - name: docker-kubernetes
          image: aadish01/docker-kubernetes
          ports:
            - containerPort: 8082

